venv_root: /opt/lick_archive
archive_service_user: archive
archive_service_group: archive
python_version: 3.9
package_install_dir: "{{ venv_root }}/lib/python{{ python_version }}/site-packages"
archive_log_dir: "{{ venv_root }}/var/log"
archive_config_dir: "{{ venv_root }}/etc"
ingest_port: 8000
cert_basename: lick_archive_selfsigned
watchdog_config: ingest_watchdog.conf
django_settings: settings.py
django_secret_keyfile: "{{ archive_config_dir }}/secret_key"
django_log: "{{ archive_log_dir }}/lsa_apps.log"
gunicorn_log: "{{ archive_log_dir }}/gunicorn.log"
redis_url: redis://localhost:6379/0
supported_instrument_dirs: ['AO', 'shane']