- name: Stop/Restart celery
  ansible.builtin.systemd:
    name: celery.service
    enabled: yes
    daemon_reload: yes
    state: "{{ archive_service_state }}"
  become: yes
  listen:
    - "restart web services"
    - "common config changed"

- name: Stop/Restart gunicorn
  ansible.builtin.systemd:
    name: gunicorn.service
    enabled: yes
    daemon_reload: no
    state: "{{ archive_service_state }}"
  become: yes
  listen: 
    - "restart web services"
    - "common config changed"

- name: Stop/Restart Ingest Service
  ansible.builtin.systemd:
    name: ingest_watchdog.service
    enabled: yes
    daemon_reload: yes
    state: "{{ archive_service_state }}"
  become: yes
  listen: 
    - "restart watchdog"
    - "common config changed"

- name: Stop/Restart Apache2
  ansible.builtin.systemd:
    name: apache2
    enabled: yes
    daemon_reload: yes
    state: "{{ archive_service_state }}"
  become: yes
  listen:
    - "restart web server"
    - "common config changed"
